server:
  port: 8084

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        #        - id: song-service
        #          uri: lb://song-service
        #          predicates:
        #            - Path=/songs/**
        - id: resources-service
          uri: lb://resources-service
          predicates:
            - Path=/resources/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
