server:
  port: 8081

spring:
  application:
    name: song-service
  flyway:
    enabled: true
    baselineOnMigrate: true
    baseline-version: 0
    locations: classpath:db/migration
    connect-retries: 5
  datasource:
    url: jdbc:postgresql://localhost:5432/introduction_to_microservices
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    root: INFO
    com:
      yum: DEBUG
    org:
      springframework:
        web: DEBUG
