server:
  port: 8082

spring:
  application:
    name: resources-service
  flyway:
    enabled: true
    baselineOnMigrate: true
    baseline-version: 0
    locations: classpath:db/migration
    Schemas: resources
    connect-retries: 5
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: BASIC
        decode404: true

logging:
  level:
    root: INFO
    com:
      epam:
        ismyrnov: DEBUG
    org:
      springframework:
        web: INFO

# discovery service will handle it
ismyrnov:
  services:
    songs:
      url: http://${SONG-SERVICE_HOST}:${SONG-SERVICE_PORT}


